### ISSUE TITLE
Can't create contact sheet

### ISSUE THREAD

**Issue by sarandafl** [amietn/vcsi#30]
Using the latest version on Mac OSX El Capitan

Getting this error:

```
Composing contact sheet...
Traceback (most recent call last):
  File "vcsi.py", line 1134, in <module>
    main()
  File "vcsi.py", line 1080, in main
    process_file(path, args)
  File "vcsi.py", line 1125, in process_file
    image = compose_contact_sheet(media_info, selected_frames, args)
  File "vcsi.py", line 677, in compose_contact_sheet
    header_font = ImageFont.truetype(args.metadata_font, args.metadata_font_size)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PIL/ImageFont.py", line 239, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PIL/ImageFont.py", line 128, in __init__
    self.font = core.getfont(font, size, index, encoding)
OSError: cannot open resource
```

This is the command I ran:
`vcsi.py file.mp4 -t -w 725 --background-color 000000 --metadata-font-color ffffff -g 4x4 -o ~/Desktop/out.png --end-delay-percent 20`

**Comment by amietn** [comment]
Currently vcsi will load its default fonts from ```/usr/share/fonts/TTF/DejaVuSans.ttf``` and ```/usr/share/fonts/TTF/DejaVuSans-Bold.ttf``` which do not exist on OSX by default.

Can you try and set the fonts you'd like to use manually using the ```---metadata-font``` and ```--timestamp-font``` arguments?

For example:

```
vcsi --metadata-font /Library/Fonts/<somefont>.ttf --timestamp-font /Library/Fonts/<somefont>.ttf
```

In order to support OSX we'd need to set some different defaults in case fonts cannot be found. Until this is fixed please try the suggestion above.

**Comment by sarandafl** [comment]
Thank you, this works!
