### ISSUE TITLE
ignore errors when processing multiple files

### ISSUE THREAD

**Issue by amietn** [amietn/vcsi#35]
Currently vcsi will exit as soon as any error occurs. This makes processing a large directory containing some non-video files impossible.

Ignore any error (just display a warning) and skip to the next file when processing multiple files at once.

**Comment by amietn** [comment]
We'll make this an option `--ignore-errors` for example.

**Comment by longsack** [comment]
Any idea when this option may be added?  :-)

**Comment by amietn** [comment]
@longsack I can't promise anything at the moment but I'll probably get this done before the end of this year.

**Comment by amietn** [comment]
@longsack This is now implemented as `--no-errors` on the master branch. It requires using `-r` (`--recursive`) for it to have an effect.
