### ISSUE TITLE
Nothing happening

### ISSUE THREAD

**Issue by sarandafl** [amietn/vcsi#36]
I have all dependencies installed, but when I run the script, nothing happens.
E.g.:
`python3.5 vcsi.py bbb_sunflower_2160p_60fps_normal.mp4 -t -w 850 -g 4x4 --background-color 000000 --metadata-font-color ffffff`

`python2.7 vcsi.py bbb_sunflower_2160p_60fps_normal.mp4 -t -w 850 -g 4x4 --background-color 000000 --metadata-font-color ffffff`

`vcsi bbb_sunflower_2160p_60fps_normal.mp4 -t -w 850 -g 4x4 --background-color 000000 --metadata-font-color ffffff`

Even with the `verbose` switch I get no output at all.

Tested on Centos7 and MacOS Sierra

**Comment by amietn** [comment]
@sarandafl That's interesting. I cannot reproduce this.

With the ```-v``` switch it should at least print some video metadata information.

Does the program end or does it keep running and never end without printing anything?

**Comment by sarandafl** [comment]
It ends. No output at all.

**Comment by amietn** [comment]
Okay. Did it stop working after a ```vcsi``` upgrade?

Can you try with commit 98fa91723441f87e24693892c4fa224955e4bc19 and report whether it changes anything?

I suspect 892d550cf1e37563a05f049155031ad9711b65c1 might have introduced a regression.

**Comment by amietn** [comment]
I was able to reproduce this on a file containing special characters. It appears that the call to [glob()](https://github.com/amietn/vcsi/blob/892d550cf1e37563a05f049155031ad9711b65c1/vcsi/vcsi.py#L1251) is returning an empty list and therefore no files are processed and vcsi simply exits.
