### ISSUE TITLE
VCSI crash

### ISSUE THREAD

**Issue by moormantom** [amietn/vcsi#37]
When I run this:
vcsi Test.avi --show-timestamp --width 1920 --grid "5x4" --end-delay-percent 10 --start-delay-percent "0" --output Test-preview.jpg

I get this error:
Traceback (most recent call last):
  File "/usr/bin/vcsi", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'vcsi==6' distribution was not found and is required by the application

I have the following packages installed on an uptodate Arch 64 system as per the vcsi dependencies list:
python-3.6.0-1
ffmpeg-1:3.2.2-2
python-numpy-1.11.3-1
python-pillow-4.0.0-2
python-jinja-2.8.1-1
python-texttable-0.8.7-2
ttf-dejavu-2.37-1

On January 6 I updated python from 3.5.2-3 to 3.6.0-1.  Before that I am pretty sure that vcsi worked.  I would downgrade python but LibreOffice requires python 3.6.

Thanks for a very usefull utility.

**Comment by moormantom** [comment]
I have found a temporary workaround.  I sim-linked the python 3.5 site-packages to 3.6:
From /usr/lib/python3.6/site-packages:
`# ln` -s /usr/lib/python3.5/site-packages/vcsi 
`# ln` -s /usr/lib/python3.5/site-packages/vcsi-6-py3.5.egg-info
Contact sheets are now produced as expected.

**Comment by amietn** [comment]
Did you try re-installing the package?

**Comment by moormantom** [comment]
Yes.
I removed the sim links and reinstalled the vcsi package.  Same result.  I put back the sim links and vcsi works as expected.  The package I reinstalled was the one I made when python 3.5 as installed.  Would that make any difference?

**Comment by amietn** [comment]
You probably have to rebuild it. Let me know if it still doesn't work.

**Comment by moormantom** [comment]
I rebuilt the package with python 3.6 installed, removed vcsi (installed with the old package), removed the sim-links and installed the rebuilt package. The site-packages are now installed under python 3.6 and VCSI now works as expected.
Thanks for the prompt feedback.
