### ISSUE TITLE
Font Issue on Centos 7, Python 3.5

### ISSUE THREAD

**Issue by gabotronix** [amietn/vcsi#38]
Hi! Thanks for this wonderful script. I love the metadata template option and I wish you can add a custom message in there too, like _Thumbnails generated by amietn._

I was able to install this on CentOS 7 and Python 3.5 but got an error during processing:

> Processing video_file.flv...
Composing contact sheet...
Traceback (most recent call last):
  File "/usr/bin/vcsi", line 11, in <module>
    load_entry_point('vcsi==6', 'console_scripts', 'vcsi')()
  File "/usr/lib/python3.5/site-packages/vcsi-6-py3.5.egg/vcsi/__init__.py", line 3, in main
  File "/usr/lib/python3.5/site-packages/vcsi-6-py3.5.egg/vcsi/vcsi.py", line 1255, in main
  File "/usr/lib/python3.5/site-packages/vcsi-6-py3.5.egg/vcsi/vcsi.py", line 1305, in process_file
  File "/usr/lib/python3.5/site-packages/vcsi-6-py3.5.egg/vcsi/vcsi.py", line 728, in compose_contact_sheet
  File "/usr/lib64/python3.5/site-packages/PIL/ImageFont.py", line 238, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/usr/lib64/python3.5/site-packages/PIL/ImageFont.py", line 127, in __init__
    self.font = core.getfont(font, size, index, encoding)
OSError: cannot open resource

You mentioned that it's looking for a DejaVuSans.ttf in /usr/share/fonts/TTF: [https://github.com/amietn/vcsi/issues/30](https://github.com/amietn/vcsi/issues/30)

This folder doesn't seem to exist on a CentOS 7 minimal install as well. Just letting you know that I got everything to work using these steps:

- Install Python 3.5:
`# yum install https://centos7.iuscommunity.org/ius-release.rpm`
`# yum install python35u python35u-libs python35u-pip python35u-devel git`

- Install DejaVuSans font and set /usr/share/fonts/TTF:
`# yum install dejavu-sans-fonts`
`# ln -s /usr/share/fonts/dejavu /usr/share/fonts/TTF`

- Install vcsi
`$ cd /usr/local/src`
`$ git clone --depth 1 https://github.com/amietn/vcsi.git`
`$ cd vcsi`
`$ python3.5 setup.py install`

- Verify vcsi installation
`$ which vcsi`
`$ /usr/bin/vcsi`
`$ vcsi --version`
`$ vcsi version 6`

- Sample output:
`$ vcsi /path/to/video_file.flv -r -t -w 800 -g 4x8 -o /path/to/thumbnails/video_file.jpg`
> Processing /path/to/video_file.flv...
Composing contact sheet...
Cleaning up temporary files...

**Comment by amietn** [comment]
You're right, I should probably mention that there's a dependency on the DejaVu font.

About the custom message, how about adding it to the end of your metadata template file?

**Comment by gabotronix** [comment]
Thanks for the hint. I was looking at the attributes without realizing that your sample template had plain texts all around. 😅
