### ISSUE TITLE
Enhancement: implement --interval

### ISSUE THREAD

**Issue by rEtSaMfF** [amietn/vcsi#42]
Allow selection of timestamps via an interval

`vcsi.py --interval=5m foo.mkv` would translate to `vcsi.py -m 5:00,10:00,15:00 foo.mkv`

Requires parsing and then passing a `capture_interval` argument to `timestamp_generator()`
and some conditionals.

**Comment by Horshev** [comment]
Hello!
This parameter is very necessary.
When will the new version be released?
Thank you!

**Comment by amietn** [comment]
@Horshev I can't say when a new feature will be implemented. I'm working on this sporadically.
