### ISSUE TITLE
crash when ffprobe doesn't pass aspect ratio

### ISSUE THREAD

**Issue by VaguelyUseful** [amietn/vcsi#45]
After an update to FFMPEG 4.0 I get the following error on a few videos in my library when ffprobe doesn't actually list an aspect ratio.

`  File "/usr/lib/python3.6/site-packages/vcsi/vcsi.py", line 161, in compute_display_resolution
    sample_aspect_ratio = self.video_stream["sample_aspect_ratio"]
KeyError: 'sample_aspect_ratio'`

I modified the vcsi.py to try: except: that line and with one that gives a 1:1 ratio when it can't find it.

`try:
    sample_aspect_ratio = self.video_stream["sample_aspect_ratio"]
except:
    sample_aspect_ratio = "1:1"
`

Uncertain if this is expected behavior from ffmpeg/ffprobe from this point forward, but this fixed the current problem for me.

**Comment by amietn** [comment]
@VaguelyUseful Can you provide me with a sample video which triggers this issue?

**Comment by amietn** [comment]
So I was able to reproduce this. Fix incoming
