### ISSUE TITLE
Ability to skip if contact sheet exists

### ISSUE THREAD

**Issue by uded** [amietn/vcsi#47]
We have a large and growing collection of videos we use for production. VCS comes in handy as we can just quickly check if the video we need is the one we think it might be.

As it is a growing collection we have a problem with duplicates JPG file creation. We run a simple `vcs *.mp4` command on each folder and that's it. It would be great to have a switch in VCS to check if there is a JPG file already created and skip if there is so. Also, not a bad option would be to force overwrites if necessary.

Sounds like a pretty simple `if` case for me, but what do I know? :-)

**Comment by amietn** [comment]
Added ```--no-overwrite``` flag to skip processing files if the corresponding output path already exists.
