### ISSUE TITLE
ImportError: No module named vcsi

### ISSUE THREAD

**Issue by wajimito** [amietn/vcsi#48]
When running:
`vcsi "/Volumes/videos/video.mp4"  -t  -w 850  -g 3x5  --end-delay-percent 20  -o output.png`
I get error: 
`Traceback (most recent call last):
  File "/usr/local/bin/vcsi", line 11, in <module>
    load_entry_point('vcsi==7', 'console_scripts', 'vcsi')()
  File "build/bdist.macosx-10.12-x86_64/egg/vcsi/__init__.py", line 2, in main
ImportError: No module named vcsi`
I'm using MacOS 10.12.6. I have installed required modules from a list.
After installation I have those folders:
- vcsi.egg-info
- vcsi
- dist
- build
- - bdist.macosx-10.12-x86_64  (THIS FOLDER IS EMPTY)
- - lib
- - - vcsi

**Comment by amietn** [comment]
@wajimito Please try installing `vcsi` from PyPi: https://pypi.org/project/vcsi/

**Comment by amietn** [comment]
Feel free to reopen if it's still an issue.
