### ISSUE TITLE
Recursive CS creation 

### ISSUE THREAD

**Issue by johannes-z** [amietn/vcsi#49]
I'm trying to create CS for my movie library. 

There are two issues I've found with recursive CS creation:

1. I cannot specify which files to include and which to exclude in the recursion. E.g. if there is a `.txt` file somewhere in a folder, vcsi crashes.  **Edit**: I found the `--ignore-errors` switch to at least prevent crashing. I guess this is good enough...

2. I cannot specify that the CS should be created at the same location the video file is at.

E.g.:

 - Movies
   - Interstellar
      - `Interstellar.mp4`
      - `Interstellar.nfo` - causes crash
      - `Interstellar.mp4.jpg` - This should be the location for the CS file

I couldn't find any options allowing me to do this.

I'm running this command in `./Movies`:

```sh
vcsi \
  -w 850 \
  -t \
  -T nw \
  -g 3x6 \
  --background-color 000000 \
  --metadata-font-color ffffff \
  --end-delay-percent 0 \
  -r \
  .
```

**Comment by amietn** [comment]
>1.  I cannot specify which files to include and which to exclude in the recursion. E.g. if there is a .txt file somewhere in a folder, vcsi crashes. Edit: I found the --ignore-errors switch to at least prevent crashing. I guess this is good enough...

Indeed, the `--ignore-errors` switch is here for this exact purpose. Another solution would be to write a wrapper script that walks the directories recursively, ignores any files you do not want to process and runs `vcsi` on the others

> 2. I cannot specify that the CS should be created at the same location the video file is at.

This is currently not supported but I can see this is a feature many people would like to have. I will be working on that soon.

**Comment by amietn** [comment]
Excluding files is now possible with `--exclude-extensions`.

For example, `vcsi -r somedir --exclude-extensions txt,png,jpg`

**Comment by amietn** [comment]
I believe this is fixed. Feel free to reopen if it's not.
