### ISSUE TITLE
vcsi fails on videos without an audio track

### ISSUE THREAD

**Issue by amietn** [amietn/vcsi#5]

**Comment by deldo1230** [comment]
hi.
What is the Python version?
I compiled with version python 3.4.4 .
But that does not work
I will need your help.

**Comment by snakebird** [comment]
I think that for videos without an audio track in `def parse_attributes` try-except block should have `except AttributeError` instead of `except KeyError`.

Besides it's a grate piece of code.

**Comment by amietn** [comment]
Thanks for the insight. Hopefully I'll get this fixed for the next release
