### ISSUE TITLE
Vertical video stretched horizontally

### ISSUE THREAD

**Issue by artur-ag** [amietn/vcsi#55]
When I try to generate thumbnails for a video recorded vertically in a smartphone, the output thumbnails are stretched to 16:9 (instead of the correct 9:16), so they stretch horizontally instead of the correct vertical layout. The content of the thumbnail is displayed correctly though, it's not rotated.

Screenshot of original video, recorded vertically:
<img src="https://user-images.githubusercontent.com/9512554/54083493-65325280-4367-11e9-97f8-10e2937a2e32.jpg" height="300" />

Output of vcsi (command `vcsi.exe vertical_test.mp4 --quality 70`):
![vertical_test mp4](https://user-images.githubusercontent.com/9512554/54083496-6c596080-4367-11e9-8a35-8c7f2765c63a.jpg)

Original video properties, as seen in MPC-HC. Note the field rotation 90°. I imagine vcsi or one of its libraries is not considering this field, because internally the video is 1920x1080, and not the expected 1080x1920.
```
Video
Format                         : AVC
Format/Info                    : Advanced Video Codec
Codec ID                       : avc1
Codec ID/Info                  : Advanced Video Coding
Width                          : 1920 pixels
Height                         : 1080 pixels
Display aspect ratio           : 16:9
Rotation                       : 90°
```

**Comment by amietn** [comment]
Indeed the rotation field is currently not used. Can you provide me with the output of the following command?

```
ffprobe -v quiet -print_format json -show_format -show_streams vertical_test.mp4
```

**Comment by artur-ag** [comment]
Sure, here's the output:  [ffprobe_out.txt](https://github.com/amietn/vcsi/files/2957517/ffprobe_out.txt)

**Comment by amietn** [comment]
Should be fixed in https://github.com/amietn/vcsi/commit/32542213e6e94f74076e76f3f52e8e028cf491ef
