### ISSUE TITLE
Thumbnails of video resolution

### ISSUE THREAD

**Issue by remlap** [amietn/vcsi#56]
HI is it possible to have each thumbnail at the videos resolution?

Thanks

**Comment by amietn** [comment]
This is currently not supported but I will try and implement it :)

**Comment by amietn** [comment]
Implemented in https://github.com/amietn/vcsi/commit/815a3a1558a7b96be7b8503e02faea59bfaacd56

**Comment by remlap** [comment]
Whenever I try to do more than one video file at the same time with -S I get this error [ERROR] Cannot use --width and --actual-size at the same time.

**Comment by amietn** [comment]
Thank you for letting me know. I will have a look at it.

**Comment by amietn** [comment]
Should be fixed in https://github.com/amietn/vcsi/commit/fcfab0d1f7f53d3007089b5f43842af41c847d8a

**Comment by remlap** [comment]
It is working now, thank you.
