### ISSUE TITLE
Should use video stream duration instead of container duration

### ISSUE THREAD

**Issue by rixtox** [amietn/vcsi#62]
When the media file has non-video streams (e.g. audio or subtitle) with duration longer than the duration of the video stream, the container duration reported from `ffprobe` is the longest duration covering all streams.

Currently vcsi uses the container duration to calculate screenshot capture timestamps, but for the case mentioned above, such calculated timestamps may cross the boundary of the video stream and causes unsuccessful screenshot capture, and eventually crash the vcsi job.

To fix the problem, vcsi should prefer the video stream duration when it's available in the media file metadata (which in most case is very fast), with the container duration as the default fallback. And provide the option to force decode and calculate accurate video stream duration when such metadata is not available (which in the worst case is very slow).

**Comment by amietn** [comment]
Should be fixed in https://github.com/amietn/vcsi/commit/7ab5119bb5918f64a876008a0ec039015bb54c64
