### ISSUE TITLE
Use --ignore-errors without -r

### ISSUE THREAD

**Issue by Chaz6** [amietn/vcsi#69]
I have a folder with a mixture of files (not just videos) and I would like to run vcsi like so (as there is one file it fails with a PIL error `raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError`):-

`$ vcsi --ignore-errors /path/to/folder/**/*.mkv`

This could potentially be achieved by adding an option `--include-extensions`

**Comment by demib72** [comment]
I run into a similar issue with corrupted files with no video-steam information. Can't figure how to skip those other than to manually delete them hours later.

**Comment by amietn** [comment]
Thank you for reporting this issue. I will have a look at this.

**Comment by demib72** [comment]
Thank you so much. In the meantime, it is possible to make a python script that iterates over the files. That is my workaround for the time being.

**Comment by amietn** [comment]
This should now be fixed in https://github.com/amietn/vcsi/commit/c9f0a42b8a32a396294b6909ae93a1f28a2960bb

The change allows to use --ignore-errors without -r
