### ISSUE TITLE
No way to process a directory containing videos?

### ISSUE THREAD

**Issue by sarandafl** [amietn/vcsi#7]
Could you maybe add an `os.walk` line where the directory could be given instead of a filename please?

**Comment by amietn** [comment]
This is definitely something I would like to see in a future release

**Comment by sarandafl** [comment]
Could you maybe add RGBA to the colour options instead of "just" RGB? Should I open a new issue?
Thanks for the script, it is awesome!

**Comment by amietn** [comment]
Yes please open another issue for that. I guess this is for the header text or the timestamp text/timestamp background rectangle that you'd like transparency?

**Comment by amietn** [comment]
@sarandafl implemented in latest commit
