### ISSUE TITLE
How to use template arguments?

### ISSUE THREAD

**Issue by NaufalAriqS21** [amietn/vcsi#78]
Hello, I want to use --template argument but I have no idea how to use it.
Tried saving template with template.txt,
The command I tried, `vcsi blablabla --template template.txt` giving no success.

So, how to use the template arguments? An example will be nice.
Thanks before.

**Comment by amietn** [comment]
See the "Metadata templates" section in the README here: https://github.com/amietn/vcsi#metadata-templates

**Comment by NaufalAriqS21** [comment]
I'm sorry but I still confused in here,  `specifiy the path to a template file`.
Can you give me one example please?

**Comment by amietn** [comment]
The path to the template file is simply the path to where the file is located. One example could be `/home/john/template.txt` or `C:\Users\John\template.txt`. Obviously, such a path will depend on the actual location of the template file you are trying to use.
