### ISSUE TITLE
Setting output file name?

### ISSUE THREAD

**Issue by AlexRuizE** [amietn/vcsi#80]
Thanks for the great work! 

Is it possible to specify the name of the output file? I'm not seeing it in the args and would be desirable to avoid manual renaming. If it's not possible yet, how would you create multiple contact sheets with as script without having to manually rename?

**Comment by GuguKatze** [comment]
Try "-o OUTPUT_PATH"? ;-)

$ vcsi -h
usage: vcsi [-h] [-o OUTPUT_PATH] [-c CONFIG]
