### ISSUE TITLE
doesn't work with files larger than 10gb

### ISSUE THREAD

**Issue by askfriends** [amietn/vcsi#87]
Hello guys;
thanks for the module.
i am trying to take screenshots from a video which is Bluray remux mkv and equals to around 30gb size.
then i tried a file who is around 9gb mp4, it didnt work, but it works fine with files smaller than 5gb.

so why it doesnt work with large files?

Its worth mentioning here that i am using the module in colab.

here is the complete error that i got.
`Processing /content/drive/Shared drives/DriveName/uploads/Aag.1994.1080p.JC.Web.Dl.AVC.AAC.DrC/Aag.1994.1080p.JC.Web.Dl.AVC.AAC.DrC.mp4...
Traceback (most recent call last):
  File "/usr/local/bin/vcsi", line 33, in <module>
    sys.exit(load_entry_point('vcsi==7.0.12', 'console_scripts', 'vcsi')())
  File "/usr/local/lib/python3.6/dist-packages/vcsi/__init__.py", line 3, in main
    vcsi.vcsi.main()
  File "/usr/local/lib/python3.6/dist-packages/vcsi/vcsi.py", line 1518, in main
    process_file(filename, args)
  File "/usr/local/lib/python3.6/dist-packages/vcsi/vcsi.py", line 1569, in process_file
    verbose=args.is_verbose)
  File "/usr/local/lib/python3.6/dist-packages/vcsi/vcsi.py", line 108, in __init__
    self.probe_media(path)
  File "/usr/local/lib/python3.6/dist-packages/vcsi/vcsi.py", line 135, in probe_media
    output = subprocess.check_output(ffprobe_command)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', '/content/drive/Shared drives/DriveName/uploads/Aag.1994.1080p.JC.Web.Dl.AVC.AAC.DrC/Aag.1994.1080p.JC.Web.Dl.AVC.AAC.DrC.mp4']' returned non-zero exit status 1.`

**Comment by amietn** [comment]
Hello @askfriends ,

I'm unable to reproduce this issue when running `vcsi` on a local 10+ GB file.
I believe this issue is related to the way the file is accessed through a mounted Google drive account from Colab and is not a `vcsi` issue.

**Comment by askfriends** [comment]
> Hello @askfriends ,
> 
> I'm unable to reproduce this issue when running `vcsi` on a local 10+ GB file.
> I believe this issue is related to the way the file is accessed through a mounted Google drive account from Colab and is not a `vcsi` issue.

Thanks for the reply.
Can you please try this in colab and figure out whats actual problem?
if you could solve it it will be really helpful.

**Comment by amietn** [comment]
I believe this is not our bug because other software running on Colab would be affected in the same way.
