### ISSUE TITLE
Full video length process

### ISSUE THREAD

**Issue by wankio** [amietn/vcsi#89]
In Sample picture, video length is 10:34 but last frame is 08:01

I'm using ezthumb, it process full length of video but this vcsi and many other thumbnailer ffmpeg,mnt,.. always do the same, can't process full length of video

So can it process full length of video ?
ty

**Comment by amietn** [comment]
`vcsi` has a default value of 7 for `--start-delay-percent` and `--end-delay-percent`, which means that by default, it will only capture frames that are not in the first 7% and not in the last 7% of the video.

Also, the timestamp of captures will be uniformly distributed in the capture window.

The `--delay-percent` option can be used to capture frames from the entire video, and you may want to tune the number of frames captured as well. For example `vcsi --delay-percent 0 video.mkv` would capture frames from the entire video.
